const Discord = require('discord.js');
const bot = new Discord.Client();
const ytdl = require('ytdl-core')

const PREFIX = 'ta ';

bot.on('ready', () =>{
    console.log('TanakinBot is now online!');
})

bot.on('message', msg=>{
    if (msg.content.startsWith("ta")) {
    let args = msg.content.substring(PREFIX.length).split(" ");

    switch(args[0]){
        case 'hi':
            msg.channel.send('Hi ' + `${msg.author}` + '!')
        break;
        case 'challenge':
            const c1 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Assault Rifles', 'Groza, AKM, Scar-L, M16A4, M416, AUG, M762, MK47, G36Z or QBZ')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/KQeDveZ.png')
            const c2 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only SMGs', 'UZI, UMP, PP-Bizon, Thompson, Vector')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/LU8fFnl.png')
            const c3 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Pistols', 'Skorpion, Sawed off, PI8C, P92, RI895, R47, P1911, Flare Gun (All drops from the Flare Gun are allowed)')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/PKiQnPK.png')
            const c4 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Snipers and DMRs', 'Kar-98, Win94, M24, AWM, SKS, Mini-14, QBU, VSS, SLR, MK14\n Pistols are allowed cause of rarity')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/HQwzcEa.png')
            const c5 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Vehicle Kills', 'Boats, Motorbikes, Cars and maybe, just maybe an Airdrop kill\n Pistols are allowed')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/OI1HhTT.png')
            const c6 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Shotguns', 'S686, S1897, S12K\n Pistols are allowed')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/4C3URBd.png')
            const c7 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('No using Scopes or Sights', '2x, 4x, 6x, 8x, Holo-Sight, Red-Dot')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/tugIZ1q.png')
            const c8 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Machine Guns', 'DP28, M249\n Pistols are allowed due to rarity')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/CuzWyH2.png')
            const c9 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Melee for the first 5 minutes', 'Must get 2 Melee Knockouts, followed by kills')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/4f6YTCt.png')
            const c10 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('No Armour', 'Helmets, Kevlar')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/NDjzFVE.png')
                const c11 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Only Grenades', 'Your first 2 kills are with a Molotov or Frag Grenade, You must use a Stun and Smoke Grenade in the game\n Pistols are allowed')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/NvVJxv5.png')
            const c12 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('No Healing', 'Cant use Syringes, Pills, Bandages or any Medkit\n only Energy Drinks are allowed')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/CuzWyH2.png')
            const c13 = new Discord.MessageEmbed()
                .setTitle('Your Challenge:')
                .setDescription('Must land in a HotSpot', 'Erangel: Pochinki, Miramar: Pecado, Vikendi: Castle, Sanhok: Paradise Resort or Bootcamp')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/vsUSmWl.png')
                var chal = [ c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13];

            var result = Math.floor((Math.random() * chal.length) + 0);
            msg.channel.send(chal[result]);
        break;
        case 'jackbox':
            const j1 = new Discord.MessageEmbed()
                .setTitle('You shall play Jackbox Party Pack 1')
                .setColor('#8E2610')
                .setImage('https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/50/73/8a/50738add-bbc2-dcd5-68c2-104d1033a4cd/source/512x512bb.jpg')
            const j5 = new Discord.MessageEmbed()
                .setTitle('You shall play Jackbox Party Pack 5')
                .setColor('#8E2610')
                .setImage('https://is5-ssl.mzstatic.com/image/thumb/Purple128/v4/7a/69/31/7a6931a3-1b89-601a-c58d-181a84acb534/source/512x512bb.jpg')
            const j6 = new Discord.MessageEmbed()
                .setTitle('You shall play Jackbox Party Pack 6')
                .setColor('#8E2610')
                .setImage('https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/a8/ea/c1/a8eac1a9-dec0-36fc-0d1a-cb64e7a1e856/source/512x512bb.jpg')    
                var jbox = [ j1, j5, j6];
            
            var result = Math.floor((Math.random() * jbox.length) + 0);
            msg.channel.send(jbox[result]);
        break;
        case 'j1':
            const ydkj15 = new Discord.MessageEmbed()
                .setTitle('You shall play You Dont Know Jack 2015')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/YDKJ-2015.png')
            const fib = new Discord.MessageEmbed()
                .setTitle('You shall play Fibbage')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/Fibbage-XL.png')
            const dr = new Discord.MessageEmbed()
                .setTitle('You shall play Drawfull')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/Drawful.png')
            const wdspud = new Discord.MessageEmbed()
                .setTitle('You shall play Word Spud')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/WordSpud.png')
            const lsw = new Discord.MessageEmbed()
                .setTitle('You shall play Lie Swatter')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/Lie-Swatter.png')  
                var jbox1 = [ ydkj15, fib, dr, wdspud, lsw];
            
            var result = Math.floor((Math.random() * jbox1.length) + 0);
            msg.channel.send(jbox1[result]);
        break;
        case 'j3':
            const quip2 = new Discord.MessageEmbed()
                .setTitle('You shall play Quiplash 2')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/04/Quiplash-2.png')
            const triv = new Discord.MessageEmbed()
                .setTitle('You shall play Trivia Murder Party')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2019/06/Trivia-Murder-Party.png')
            const guess = new Discord.MessageEmbed()
                .setTitle('You shall play Guesspionage')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2019/06/Guesspionage.png')
            const tko = new Discord.MessageEmbed()
                .setTitle('You shall play Tee KO')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/04/Tee-KO-No-Text.png')
            const fak = new Discord.MessageEmbed()
                .setTitle('You shall play Fakin It')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Fakin-It-o9bdi6nb0i862bttrhuy7uq1doi27sshp5s6uwefwg.png')  
                var jbox3 = [ quip2, triv, guess, tko, fak];
            
            var result = Math.floor((Math.random() * jbox3.length) + 0);
            msg.channel.send(jbox3[result]);
        break;
        case 'j4':
            const fib3 = new Discord.MessageEmbed()
                .setTitle('You shall play Fibbage 3')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Fibbage-3-o9m4ct31j2q2m2mq2csw0io1r9y51qiqfjnfcz9af4.png')
            const surv = new Discord.MessageEmbed()
                .setTitle('You shall play Survive the Internet')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Survive-The-Internet-o8lm9isax0m6ch3qe0r5oui8vnjfnkvgm7wloo8qgw.png')
            const mon = new Discord.MessageEmbed()
                .setTitle('You shall play Monster seeking Monster')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Monster-Seeking-Monster-o8lm9xtpyd6ri8hvy796sqpmdthb2qj60acdd3mfpc.png')
            const brak = new Discord.MessageEmbed()
                .setTitle('You shall play Bracketeering')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2019/05/Bracketeering.png')
            const civ = new Discord.MessageEmbed()
                .setTitle('You shall play Civic Doodle')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Civic-Doodle-o8lmb36mb2rdp2tt8p4rug9wirtghf3ctz1qh9x43k.png')  
                var jbox4 = [ fib3, surv, mon, brak, civ];
            
            var result = Math.floor((Math.random() * jbox4.length) + 0);
            msg.channel.send(jbox4[result]);
        break;
        case 'j5':
            const ydkj = new Discord.MessageEmbed()
                .setTitle('You shall play You Dont Know Jack')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/1-o7yth6on4l664fpkx38r2rm6ohizxr0zrj8jjpuscg.png')
            const split = new Discord.MessageEmbed()
                .setTitle('You shall play Split the Room')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/2-o7yth8kbi98qrnmum4207r53v99qd58gfsjii9s000.png')
            const mad = new Discord.MessageEmbed()
                .setTitle('You shall play Mad Verse City')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/3-o7ythbdu2rclqhir5n9vx8fhnevu08jng6hyy3nthc.png')
            const ptnt = new Discord.MessageEmbed()
                .setTitle('You shall play Patently Stupid')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/4-o7ythg310xj1cjbxe7b0rp8smc8o2q2b4trechgum8.png')
            const dr2 = new Discord.MessageEmbed()
                .setTitle('You shall play Drawfull 2')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2019/07/drawful2.png')
                var jbox5 = [ ydkj, split, mad, ptnt, dr2];
            
            var result = Math.floor((Math.random() * jbox5.length) + 0);
            msg.channel.send(jbox5[result]);
        break;
        case 'j6':
            const murder = new Discord.MessageEmbed()
                .setTitle('You shall play Trivia Murder Party')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/TMP2_LogoTransparent.png')
            const role = new Discord.MessageEmbed()
                .setTitle('You shall play Role Models')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/roleModelsLogo-ocw6829kh5ozychj8e9nlp5q8rt61p2snr0cxro268.png')
            const joke = new Discord.MessageEmbed()
                .setTitle('You shall play Joke Boat')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/jokeBoatLogo-ocw687wlm5wpw09cbgpf0nqht31dbvp6oix9tffp4w.png')
            const diction = new Discord.MessageEmbed()
                .setTitle('You shall play Dictionarium')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/dictionariumLogo-ocw680dw3hmfb4k9jdgegpmt202fmavbzhpdz7quio.png')
            const button = new Discord.MessageEmbed()
                .setTitle('You shall play Push the Button')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/05/PTB-LOGO-transparent.png')  
                var jbox6 = [ murder, role, joke, diction, button];
            
            var result = Math.floor((Math.random() * jbox6.length) + 0);
            msg.channel.send(jbox6[result]);
        break;
        case 'j7':
            const quip3 = new Discord.MessageEmbed()
                .setTitle('You shall play Quiplash 3')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/09/q3_logo_900_v1-e1600202564714.png')
            const dev = new Discord.MessageEmbed()
                .setTitle('You shall play The Devils and the Details')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Logo-e1600202591448-oviozcq8tgqhficc2w3jm9idgumrmd5833ikzdosn4.png')
            const champ = new Discord.MessageEmbed()
                .setTitle("You shall play Champ'd up")
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Game-Logo-e1600202544165-ovioy4jtw9209u4i8v02v2npjqoikl9u90urfdiark.png')
            const talk = new Discord.MessageEmbed()
                .setTitle('You shall play Talking Points')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/elementor/thumbs/Talking-Points-logo-square-e1600202475995-oviowboysol80qqprkytl10wk5k6th4d03u9ba6gow.png')
            const blath = new Discord.MessageEmbed()
                .setTitle('You shall play Blather Round')
                .setColor('#8E2610')
                .setImage('https://jackboxgames.b-cdn.net/wp-content/uploads/2020/09/BlatherLogoTransparent-e1600202605496.png')  
                var jbox7 = [ quip3, dev, champ, talk, blath];
            
            var result = Math.floor((Math.random() * jbox7.length) + 0);
            msg.channel.send(jbox7[result]);
        break;
        case 'pubg':
            const emap = new Discord.MessageEmbed()
                .setTitle('You shall land in Erangel')
                .setColor('#8E2610')
                .setImage('https://d22kb4lu6hci84.cloudfront.net/assets/editorial/2017/04/full-map-and-all-locations-playerunknown-battlegrounds-1.jpg')
            const vmap = new Discord.MessageEmbed()
                .setTitle('You shall land in Vikendi')
                .setColor('#8E2610')
                .setImage('https://gamepedia.cursecdn.com/battlegrounds_gamepedia_en/f/fb/Vikendi_Map.jpg?version=cb564caad8cccb4d4c127a7c7045eb6b')
            const smap = new Discord.MessageEmbed()
                .setTitle('You shall land in Sanhok')
                .setColor('#8E2610')
                .setImage('https://gamepedia.cursecdn.com/battlegrounds_gamepedia_en/6/62/Sanhok-map.jpeg?version=7cdf54ad83186f86a47f3daf7b98710d')
            const mmap = new Discord.MessageEmbed()
                .setTitle('You shall land in Miramar')
                .setColor('#8E2610')
                .setImage('https://gamepedia.cursecdn.com/battlegrounds_gamepedia_en/c/c0/Miramar_EN.jpeg?version=cdf20fb046496bc117415d86c77a3c59')    
                var pmaps = [ emap, mmap, smap, vmap];
            
            var result = Math.floor((Math.random() * pmaps.length) + 0);
            msg.channel.send(pmaps[result]);
        break;
        
        case 'erangel':
            const zharki = new Discord.MessageEmbed()
                .setTitle('You shall land in Zharki')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/zharki.PNG')
            const severny = new Discord.MessageEmbed()
                .setTitle('You shall land in Severny')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/severny.PNG')
            const stalber = new Discord.MessageEmbed()
                .setTitle('You shall land in Stalber')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/stalber.PNG')
            const kameshki = new Discord.MessageEmbed()
                .setTitle('You shall land in Kameshki')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/kameshki.PNG')
            const yasnaya = new Discord.MessageEmbed()
                .setTitle('You shall land in Yasnaya Polyana')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/yasnaya-polyana.PNG')
            const mansion = new Discord.MessageEmbed()
                .setTitle('You shall land in Mansion')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/mansion.PNG')
            const lipovka = new Discord.MessageEmbed()
                .setTitle('You shall land in Lipovka')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/lipovka.PNG')
            const prison = new Discord.MessageEmbed()
                .setTitle('You shall land in Prison')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/prison.jpg')
            const shelter = new Discord.MessageEmbed()
                .setTitle('You shall land in Shelter')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/shelter.jpg')
            const farm = new Discord.MessageEmbed()
                .setTitle('You shall land in Farm')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/farm.PNG')
            const mylta = new Discord.MessageEmbed()
                .setTitle('You shall land in Mylta')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/mylta.jpg')
            const power = new Discord.MessageEmbed()
                .setTitle('You shall land in Mylta Power')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/mylta-power-factory.PNG')
            const shooting = new Discord.MessageEmbed()
                .setTitle('You shall land in Shooting Range')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/shooting.jpg')
            const rozhok = new Discord.MessageEmbed()
                .setTitle('You shall land in Rozhok')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/Rozhok.PNG')
            const school = new Discord.MessageEmbed()
                .setTitle('You shall land in School')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/school-and-apartment.PNG')
            const ruins = new Discord.MessageEmbed()
                .setTitle('You shall land in Ruins')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/ruins.jpg')
            const pochinki = new Discord.MessageEmbed()
                .setTitle('You shall land in Pochinki')
                .setColor('#8E2610')
                .setImage('https://vignette.wikia.nocookie.net/playerunknowns-battlegrounds/images/d/dc/PUBG_Erangel_Pochinki.jpeg/revision/latest?cb=20180331223735')
            const georgopool = new Discord.MessageEmbed()
                .setTitle('You shall land in Georgopool')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/Georgopool.PNG')
            const gatka = new Discord.MessageEmbed()
                .setTitle('You shall land in Gatka')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/gtaka.jpg')
            const hospital = new Discord.MessageEmbed()
                .setTitle('You shall land in Hospital')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/hospital.PNG')
            const quarry = new Discord.MessageEmbed()
                .setTitle('You shall land in Quarry')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/quarry.jpg')
            const primorsk = new Discord.MessageEmbed()
                .setTitle('You shall land in Primorsk')
                .setColor('#8E2610')
                .setImage('https://www.dailyesports.gg/wp-content/uploads/2018/09/prim.jpg')
            const ferry = new Discord.MessageEmbed()
                .setTitle('You shall land in Ferry Pier')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/ferry-power.PNG')
            const military = new Discord.MessageEmbed()
                .setTitle('You shall land in Military Base')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/sosnovka-military-base.PNG')
            const novorepnoye = new Discord.MessageEmbed()
                .setTitle('You shall land in Novorepnoye')
                .setColor('#8E2610')  
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map/all-maps/thumbs/novorepnoye.PNG')      
            
            var era = [zharki, severny, stalber, kameshki, yasnaya, yasnaya, yasnaya, mansion, lipovka, prison, shelter, shelter, shelter, shelter, farm, mylta, mylta, mylta, mylta, mylta, mylta, power, power, power, shooting, rozhok, rozhok, school, school, school, school, school, school, school, school, ruins, ruins, pochinki, pochinki, pochinki, pochinki, pochinki, pochinki, pochinki, pochinki, georgopool, georgopool, georgopool, georgopool, georgopool, georgopool, georgopool, georgopool, georgopool, georgopool, gatka, gatka, hospital, quarry, primorsk, primorsk, primorsk, primorsk,ferry, military, military, military, military, military, military, military, novorepnoye, novorepnoye, novorepnoye];
            var result = Math.floor((Math.random() * era.length) + 0);
            msg.channel.send(era[result]);
        break;
        case 'vikendi': 
            const port = new Discord.MessageEmbed()
                .setTitle('You shall land in Port')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/port.png')
            const zabava = new Discord.MessageEmbed()
                .setTitle('You shall land in Zabava')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/zabava.png')
            const cosmodrome = new Discord.MessageEmbed()
                .setTitle('You shall land in Cosmodrome')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/cosmodrome.png')
            const trevno = new Discord.MessageEmbed()
                .setTitle('You shall land in Trevno')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/trevno.png')
            const krichas = new Discord.MessageEmbed()
                .setTitle('You shall land in Krichas')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/krichas.png')
            const coal = new Discord.MessageEmbed()
                .setTitle('You shall land in Coal Mine')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/coal_mine.png')
            const dobro = new Discord.MessageEmbed()
                .setTitle('You shall land in Dobro Mesto')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/dobro_mesto.png')
            const goroka = new Discord.MessageEmbed()
                .setTitle('You shall land in Goroka')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/goroka.png')
            const kreznic = new Discord.MessageEmbed()
                .setTitle('You shall land in Mt. Kreznic')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/mount_kreznic.png')
            const peshkova = new Discord.MessageEmbed()
                .setTitle('You shall land in Peshkova')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/peshkova.png')
            const villa = new Discord.MessageEmbed()
                .setTitle('You shall land in Villa')
                .setColor('#8E2610')
                .setImage('https://tipsmake.com/data/images/pubg-mobile-vng-the-most-fierce-fighting-areas-at-vikendi-picture-1-pLknp0Eqp.jpg')
            const podvosto = new Discord.MessageEmbed()
                .setTitle('You shall land in Podvosto')
                .setColor('#8E2610')
                .setImage('https://statics.sportskeeda.com/editor/2020/04/82f49-15867707332311-800.jpg')
            const cement = new Discord.MessageEmbed()
                .setTitle('You shall land in Cement Factory')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/cement_factory.png')
            const lumber = new Discord.MessageEmbed()
                .setTitle('You shall land in Lumber Yard')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/lumber_yard.png')
            const vihar = new Discord.MessageEmbed()
                .setTitle('You shall land in Vihar')
                .setColor('#8E2610') 
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/vihar.png') 
            const movatra = new Discord.MessageEmbed()
                .setTitle('You shall land in Movatra')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/movatra.png')
            const dino = new Discord.MessageEmbed()
                .setTitle('You shall land in Dino Park')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/dino_park.png')
            const sawmill = new Discord.MessageEmbed()
                .setTitle('You shall land in Sawmill')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/sawmill.png')
            const abbey = new Discord.MessageEmbed()
                .setTitle('You shall land in Abbey')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map-location-information/abbey.jpg')
            const volnova = new Discord.MessageEmbed()
                .setTitle('You shall land in Volnova')
                .setColor('#8E2610')
                .setImage('https://bang-phinf.pstatic.net/a/30ac8g/c_a69Ud018bng5x7yygbewtj9_g57aw.png?type=w660')
            const hot = new Discord.MessageEmbed()
                .setTitle('You shall land in Hot Springs')
                .setColor('#8E2610')  
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/hot_springs.png') 
            const cantra = new Discord.MessageEmbed()
                .setTitle('You shall land in Cantra')
                .setColor('#8E2610')   
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/cantra.png')
            const milnar = new Discord.MessageEmbed()
                .setTitle('You shall land in Milnar')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/milnar.png')
            const pilnec = new Discord.MessageEmbed()
                .setTitle('You shall land in Pilnec')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/pilnec.png')
            const winery = new Discord.MessageEmbed()
                .setTitle('You shall land in Winery')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/vikendi/winery.png')
                
                var vik = [port, zabava, zabava, cosmodrome, cosmodrome, cosmodrome, cosmodrome, trevno, trevno, krichas, krichas, krichas, coal, coal, coal, coal, coal, coal, coal, dobro, dobro, dobro, dobro, dobro, goroka, goroka, goroka, goroka, goroka, goroka, kreznic, kreznic, kreznic, peshkova, peshkova, peshkova, peshkova, villa, villa, villa, villa, podvosto, podvosto, podvosto, podvosto, cement, cement, cement, lumber, lumber, vihar, vihar, vihar, vihar, movatra, movatra, movatra, movatra, dino, dino, dino, dino, sawmill, sawmill, abbey, abbey, volnova, volnova, volnova, volnova, hot, hot, cantra, cantra, cantra, milnar, milnar, pilnec, pilnec, pilnec, winery, winery, winery, winery, winery];
            var result = Math.floor((Math.random() * vik.length) + 0);
            msg.channel.send(vik[result]);
        break;
        case 'sanhok':
            const ha = new Discord.MessageEmbed()
                .setTitle('You shall land in Ha Tinh')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/ha_tinh.jpg')
            const khao = new Discord.MessageEmbed()
                .setTitle('You shall land in Khao')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/khao.jpg')
            const tat = new Discord.MessageEmbed()
                .setTitle('You shall land in Tat Mok')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/tat_mok.jpg')
            const mongnai = new Discord.MessageEmbed()
                .setTitle('You shall land in Monganai')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/mongnai.jpg')
            const paradise = new Discord.MessageEmbed()
                .setTitle('You shall land in Paradise Resort')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/paradise_resort.jpg')
            const alpha = new Discord.MessageEmbed()
                .setTitle('You shall land in Camp Alpha')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/camp_alpha.jpg')
            const bootcamp = new Discord.MessageEmbed()
                .setTitle('You shall land in Bootcamp')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/bootcamp.jpg')
            const bravo = new Discord.MessageEmbed()
                .setTitle('You shall land in Camp Bravo')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/camp_bravo.jpg')
            const bhan = new Discord.MessageEmbed()
                .setTitle('You shall land in Bhan')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/bhan.jpg')
            const lakawi = new Discord.MessageEmbed()
                .setTitle('You shall land in Lakawi')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/lakawi.jpg')
            const squarry = new Discord.MessageEmbed()
                .setTitle('You shall land in Quarry')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/quarry.jpg')
            const sruins = new Discord.MessageEmbed()
                .setTitle('You shall land in Ruins')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/ruins.jpg')
            const pai = new Discord.MessageEmbed()
                .setTitle('You shall land in Pai Nan')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/pai_nan.jpg')
            const tambang = new Discord.MessageEmbed()
                .setTitle('You shall land in Tambang')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/tambang.jpg')
            const kampong = new Discord.MessageEmbed()
                .setTitle('You shall land in Kampong')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/kampong.jpg')
            const na = new Discord.MessageEmbed()
                .setTitle('You shall land in Na Kham')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/na_kham.jpg')
            const cave = new Discord.MessageEmbed()
                .setTitle('You shall land in Cave')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/cave.jpg')
            const charlie = new Discord.MessageEmbed()
                .setTitle('You shall land in Camp Charlie')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/camp_charlie.jpg')
            const sahmee = new Discord.MessageEmbed()
                .setTitle('You shall land in Sahmee')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/sahmee.jpg')
            const docks = new Discord.MessageEmbed()
                .setTitle('You shall land in Docks')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/docks.jpg')
            const ban = new Discord.MessageEmbed()
                .setTitle('You shall land in Ban Tai')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/sanhok/ban_tai.jpg')
        
            var san = [ha, khao, tat, mongnai, paradise, paradise, paradise, paradise, alpha, alpha, alpha, bootcamp, bootcamp, bootcamp, bootcamp, bootcamp, bravo, bravo, bravo, bhan, bhan, bhan, lakawi, squarry, squarry, squarry, squarry, sruins, sruins, sruins, sruins, pai, pai, pai, pai, pai, tambang, kampong, kampong, kampong, na, na, cave, cave, cave, cave, charlie, charlie, charlie, charlie, sahmee, sahmee, docks, docks, docks, ban, ban];
            var result = Math.floor((Math.random() * san.length) + 0);
            msg.channel.send(san[result]);
        break;
        case 'miramar':
            const alcantara = new Discord.MessageEmbed()
                .setTitle('You shall land in Alcantara')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/alcantara.jpg')
            const cobreria = new Discord.MessageEmbed()
                .setTitle('You shall land in La Cobreria')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/la_cobreria.jpg')
            const torre = new Discord.MessageEmbed()
                .setTitle('You shall land in Torre Ahumada')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/torre_ahumada.jpg')
            const campo = new Discord.MessageEmbed()
                .setTitle('You shall land in Campo Militar')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/campo_militar.jpg')
            const cruz = new Discord.MessageEmbed()
                .setTitle('You shall land in Cruz del Valle')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/cruz_del_valle.jpg')
            const tierra = new Discord.MessageEmbed()
                .setTitle('You shall land in Tierra Bronca')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/tierra_bronca.jpg')
            const trailer = new Discord.MessageEmbed()
                .setTitle('You shall land in Trailer Park')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/trailer_park.png')
            const crater = new Discord.MessageEmbed()
                .setTitle('You shall land in Crater Fields')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/crater_fields.png')
            const water = new Discord.MessageEmbed()
                .setTitle('You shall land in Water Treatment')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/water_treatment.jpg')
            const azahar = new Discord.MessageEmbed()
                .setTitle('You shall land in El Azahar')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/el_azahar.jpg')
            const pozo = new Discord.MessageEmbed()
                .setTitle('You shall land in El Pozo')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/el_pozo.jpg')
            const martin = new Discord.MessageEmbed()
                .setTitle('You shall land in San Martin')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/san_martin.jpg')
            const hacienda = new Discord.MessageEmbed()
                .setTitle('You shall land in Hacienda Del Patron')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/hacienda.jpg')
            const junkyard = new Discord.MessageEmbed()
                .setTitle('You shall land in Junkyard')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/junkyard.jpg')
            const monte = new Discord.MessageEmbed()
                .setTitle('You shall land in Monte Nuevo')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/monte_nuevo.jpg')
            const grid = new Discord.MessageEmbed()
                .setTitle('You shall land in Power Grid')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/power_grid.jpg')
            const grave = new Discord.MessageEmbed()
                .setTitle('You shall land in Graveyard')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/graveyard.jpg')
            const minas = new Discord.MessageEmbed()
                .setTitle('You shall land in Minas Generales')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/minas_generales.jpg')
            const impala = new Discord.MessageEmbed()
                .setTitle('You shall land in Impala')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/impala.jpg')
            const pecado = new Discord.MessageEmbed()
                .setTitle('You shall land in Pecado')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/pecado.jpg')
            const bendita = new Discord.MessageEmbed()
                .setTitle('You shall land in La Bendita')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/la_bendita.jpg')
            const ladrillera = new Discord.MessageEmbed()
                .setTitle('You shall land in Ladrillera')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/ladrillera.png')
            const chumacera = new Discord.MessageEmbed()
                .setTitle('You shall land in Chumacera')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/chumacera.jpg')
            const leones = new Discord.MessageEmbed()
                .setTitle('You shall land in Los Leones')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/los_leones.jpg')
            const valle = new Discord.MessageEmbed()
                .setTitle('You shall land in Valle Del Mar')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/valle_del_mar.jpg')
            const puerto = new Discord.MessageEmbed()
                .setTitle('You shall land in Puerto Paraiso')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/puerto_paraiso.jpg')
            const mprison = new Discord.MessageEmbed()
                .setTitle('You shall land in Prison')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/prison.jpg')
            const higos = new Discord.MessageEmbed()
                .setTitle('You shall land in Los Higos')
                .setColor('#8E2610')
                .setImage('https://storage.googleapis.com/jsdiscordbots_drops/miramar/los_higos.jpg')

            var mir = [alcantara, cobreria, cobreria, cobreria, torre, torre, campo, campo, cruz, cruz, cruz, cruz, tierra, tierra, trailer, crater, crater, crater, crater, water, water, water, water, water, azahar, azahar, azahar, azahar, pozo, pozo, pozo, pozo, pozo, pozo, martin, martin, martin, martin, martin, hacienda, hacienda, junkyard, junkyard, junkyard, monte, monte, monte, grid, grid, grid, grave, grave, grave, minas, minas, impala, impala, impala, impala, pecado, pecado, pecado, pecado, pecado, pecado, pecado, pecado, pecado, pecado, bendita, bendita, bendita, bendita, ladrillera, ladrillera, chumacera, chumacera, chumacera, leones, leones, leones, leones, leones, leones, leones, valle, valle, valle, valle, puerto, puerto, mprison, higos];
            var result = Math.floor((Math.random() * mir.length) + 0);
            msg.channel.send(mir[result]);
        break;
        case 'imposter': case 'imposters': case 'imp':
            const i1 = new Discord.MessageEmbed()
                .setTitle('There shall be 1 Imposter')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/VlA4fYn.png')
            const i2 = new Discord.MessageEmbed()
                .setTitle('There shall be 2 Imposters')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/3dOMVTr.png')
            const i3 = new Discord.MessageEmbed()
                .setTitle('There shall be 3 Imposters')
                .setColor('#8E2610')
                .setImage('https://i.imgur.com/JAPB0it.png')    
                var imp = [ i1, i2, i3];
            
            var result = Math.floor((Math.random() * imp.length) + 0);
            msg.channel.send(imp[result]);
        break;
        case 'amongus': case 'amongusmap': case 'au': case 'aumap':
            const pol = new Discord.MessageEmbed()
                .setTitle('Play in POLUS')
                .setColor('#092582')
                .setImage('https://vignette.wikia.nocookie.net/among-us-wiki/images/6/67/PolusButton.png/revision/latest?cb=20201006103729')
            const mira = new Discord.MessageEmbed()
                .setTitle('Play in MIRA HQ')
                .setColor('#b51818')
                .setImage('https://vignette.wikia.nocookie.net/among-us-wiki/images/4/4d/MIRAHQButton.png/revision/latest/scale-to-width-down/185?cb=20201006103813')
            const skeld = new Discord.MessageEmbed()
                .setTitle('Play in The Skeld')
                .setColor('#9c8686')
                .setImage('https://vignette.wikia.nocookie.net/among-us-wiki/images/c/c9/TheSkeldButton.png/revision/latest/scale-to-width-down/185?cb=20201006103842')    
                var mapss = [ pol, mira, skeld];
            
            var result = Math.floor((Math.random() * mapss.length) + 0);
            msg.channel.send(mapss[result]);
        break;
        case 'profile':
            const created = msg.author.createdAt
            const userid = msg.author.id
            const username = msg.author.username
            const usertag = msg.author.tag    

            const profile = new Discord.MessageEmbed()
                .setTitle(username)
                .addField('User Tag ', usertag)
                .addField('Account created:', created)
                .addField('User ID: ', userid)
                .setThumbnail(msg.author.avatarURL('png', 0, '1024' ))
            msg.channel.send(profile)
        break;
        case 'avatar':
            msg.channel.send(msg.author.displayAvatarURL())
        break;
        case 'help':
            const helpembed = new Discord.MessageEmbed()
                .setTitle('***Omnis Bot Help***')
                .setColor('#8E2610')
                .addField('----------------------------------------------','**Games**')
                .addField('*Jackbox*','`ta jackbox` to randomly select which Jackbox game to play \n `ta j1, j3, j4, j5, j6, j7` to randomly select which minigame to play within a Jackbox game' )
                .addField('*PUBG*', '`ta pubg` to randomly select which PUBG map to play on \n `ta sanhok, miramar, vikendi, erangel` to randomly select a place to land in the chosen map \n `ta map sanhok, miramar, vikendi, erangel` to display the appropriate map for each prompt \n `ta challenge` to randomly select a challenge ' )
                .addField('*Among Us*', '`ta imp` to randomly select the number of imposters in a game \n `ta au` to randomly select the map you want to play in' )
                .addField('----------------------------------------------','**Miscellaneous and Music**')
                .addField('*Music*','`ta play <songname>` to play a certain song, (ignore the pointed brackets) \n `ta clear <number>` to clear a certain amount of lines, abuse will result in mute or ban')
                .addField('*Miscellaneous*','`ta profile` to view data on the users profile \n `ta avatar` to get a direct link to the users profile picture')
                .addField('***This bot is still in development and there are obviously going to be numerous bugs, please be patient with updates***','**----------------------------------------------**')
                .setAuthor('Tanakiin')
                msg.channel.send(helpembed)
        break;
    }}
    const premap = 'ta map '
    let args2 = msg.content.substring(premap.length).split(" ");
    switch(args2[0]){
        case 'erangel':
            const erangel = new Discord.MessageEmbed()
                .setTitle('Erangel')
                .setColor('#8E2610')
                .setImage('https://pbs.twimg.com/media/DpUL6T3VsAARovR?format=jpg&name=large')
            msg.channel.send(erangel)
        break;
        case 'sanhok':
            const sanhok = new Discord.MessageEmbed()
                .setTitle('Sanhok')
                .setColor('#8E2610')
                .setImage('https://www.esportsportal.com/wp-content/uploads/2019/05/950px-Sanhok-map-750x750.jpeg')
            msg.channel.send(sanhok)
        break;
        case 'miramar':
            const miramar = new Discord.MessageEmbed()
                .setTitle('Miramar')
                .setColor('#8E2610')
                .setImage('https://www.windowscentral.com/sites/wpcentral.com/files/styles/w830/public/field/image/2017/12/pubg-miramar-map.jpg?itok=PeQaNWJl')
            msg.channel.send(miramar)
        break;
        case 'vikendi':
            const vikendi = new Discord.MessageEmbed()
                .setTitle('Vikendi')
                .setColor('#8E2610')
                .setImage('https://zilliongamer.com/uploads/pubg-mobile/map-location-information/pubg-mobile-vikendi.jpg')
            msg.channel.send(vikendi)
        break;
    };
})
bot.login(process.env.token);
